spring:
  application:
    name: zeroton
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/test?authSource=admin


  jpa:
    hibernate:
      ddl-auto: create  # create, update, none
    show-sql: true
    generate-ddl: true
